# Comment to a new issue.
issuesOpened: >
  Thank you for raising an issue. <br>We will try and get back to you as soon as possible.
  
  ⚠️Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible.<br>
  **If not, the issue will be closed or not replied.**<br><br>
  
  이슈를 올려주셔서 감사합니다.<br>
  담당자가 확인 후 빠른 시일 내로 답변할 예정입니다.
  
  ⚠️이슈 템플릿에 따라 내용을 충분히 작성하였는지, 그리고 **영문**으로 작성하였는지 확인해주세요.<br>
  해당 내용을 준수하지 않았을 경우, 이슈는 클로즈되거나 답변이 없을 수 있습니다.<br>
  꼭 위의 사항을 준수해주세요.
